name: Autofix

on:
  schedule:
  - cron: '*/2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'rust-lang/glacier'

    steps:
    - uses: actions/checkout@v1
    - name: Configure Git
      run: |
        git config --global user.name "staceb"
        git config --global user.email "staceb@users.noreply.github.com"
    - run: echo ${{ github.repository }}


