name: Test Fork

on:
  schedule:
  - cron: '*/2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'staceb/rust-test'

    steps:
      - uses: actions/checkout@v1
      - name: Check repo value
        run: echo ${{ github.repository }}
