name: Test

on:
  schedule:
  - cron: '*/2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Check repo value
        run: echo ${{ github.repository }}
